site_name: DE Project Blog
site_description: Documentation for the DE Project
site_url: https://ani-kmr.github.io/site/

use_directory_urls: true

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.code.fold
    - content.tabs.links
    - footer.social
    - footer.navigation
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - About: home/about.md
  - Layout: home/layout.md
  - Tools & Technologies: home/tools_technologies.md
  - Tags: tags/tags.md
  - Projects:
      - Airline:
          - Overview: projects/airline/airline.md
          - Data Exploration: projects/airline/airline_data_exploration.md
          - Modeling: projects/airline/airline_modeling.md
          - Code Templates: projects/airline/airline_code_templates.md
          - Orchestration: projects/airline/airline_orchestration.md
          - Deployment: projects/airline/airline_deployment.md
      - Market Data:
          - Overview: projects/market/market_data.md
          - Data Exploration: projects/market/market_data_exploration.md
          - Modeling: projects/market/market_data_modeling.md
          - Code Templates: projects/market/market_data_code_templates.md
          - Orchestration: projects/market/market_data_orchestration.md
          - Deployment: projects/market/market_data_deployment.md
      - Stock Prices:
          - Overview: projects/Stock/stock_prices.md
          - Data Exploration: projects/Stock/stock_data_exploration.md
          - Modeling: projects/Stock/stock_data_modeling.md
          - Code Templates: projects/Stock/stock_data_code_templates.md
          - Orchestration: projects/Stock/stock_data_orchestration.md
          - Deployment: projects/Stock/stock_data_deployment.md
      - Others: projects/others.md
  - Releases:
      - Airline:
          - Change:
              - v1.0.0: releases/airline/change/v1.0.0.md
          - Fix:
              - v1.0.0: releases/airline/fix/v1.0.0.md
      - Market Data:
          - Change:
              - v1.0.0: releases/market/change/v1.0.0.md
          - Fix:
              - v1.0.0: releases/market/fix/v1.0.0.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search:
      lang: en
      separator: '[\s\-]+'
  - tags:
      listings_map:
        scoped:
          scope: true

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/dashboard/home
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/feed/
    - icon: fontawesome/solid/paper-plane
      link: mailto:anilkun42@gmail.com

copyright: |
  Copyright Â© 2016-2025 Anil Kumar K
  Licensed under the [MIT License](https://opensource.org/licenses/MIT).
